workflows:
  ios-workflow:
    name: ios_workflow
    environment:
      groups:
        - appstore_credentials
      vars:
        XCODE_WORKSPACE: "My First iOS App.xcodeproj"  # PUT YOUR WORKSPACE NAME HERE
        XCODE_SCHEME: "My First iOS App" # PUT THE NAME OF YOUR SCHEME HERE
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain to be used for code signing using Codemagic CLI 'keychain' command
        script: |
                    keychain initialize
      - name: Fetch signing files
        script: |
                    app-store-connect fetch-signing-files $(xcode-project detect-bundle-id) --type IOS_APP_STORE --create
      - name: Add certificates to keychain
        script: |
                    keychain add-certificates 
      - name: Increment build number
        script: agvtool new-version -all $(($BUILD_NUMBER +1))
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Build ipa for distribution
        script: xcode-project build-ipa --project "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME" 
      - name: Release notes
        script: |
            CURRENT_BRANCH=$(git branch --show-current )
            TITLE="This build is from the \`${CURRENT_BRANCH}\` branch.\n"
            echo $CURRENT_BRANCH
            COMMITS="$(git log master -25 --format=format:" • %s")"

            FORMATTEDCOMMITS=""
            while read line; do FORMATTEDCOMMITS=$FORMATTEDCOMMITS$line"\n"; done <<< "$COMMITS"

            MASTERCOMMITS="\nList of the last 25 commits in the master branch:\n$FORMATTEDCOMMITS"

            CONTENT=${TITLE}${MASTERCOMMITS}
            HEADER="[{\"language\":\"en-US\",\"text\":\""
            FOOTER="\"}]"

            RELEASENOTES="${HEADER}${CONTENT}${FOOTER}"

            echo $RELEASENOTES
            chmod +x release_notes.json
            cat <<< "$RELEASENOTES" > $CM_BUILD_DIR/release_notes.json
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY      # Contents of the API key
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER    # Alphanumeric value that identifies the API key
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID   
